# Generated by Django 2.0.4 on 2018-04-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorabikeapp', '0002_auto_20180422_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rssi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='snr',
            field=models.FloatField(default=0),
        ),
    ]
