# Generated by Django 2.0.4 on 2018-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorabikeapp', '0003_auto_20180423_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cordinate_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='cordinate_y',
            field=models.FloatField(default=0),
        ),
    ]
