# Generated by Django 2.0.4 on 2018-04-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorabikeapp', '0005_auto_20180424_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='track_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
