# Generated by Django 2.0.4 on 2018-04-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorabikeapp', '0007_location_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='device_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
